export type Title = {
  slug: string;
  title: string;
  meta: string;
  year: string;
  maturity: string;
  runtime: string;
  quality: string;
  match: string;
  genre: string;
  description: string;
  cast: string[];
  director: string;
  original?: boolean;
  posterClass: string;
};

export const titles: Title[] = [
  {
    slug: "vinewood-nights",
    title: "Vinewood Nights",
    meta: "Crime · 2026",
    year: "2026",
    maturity: "18+",
    runtime: "2h 07m",
    quality: "4K",
    match: "98%",
    genre: "Crime / Thriller",
    description:
      "Gdy światła premier gasną, zaczyna się prawdziwe Vinewood. Młody producent odkrywa układ, który może wynieść go na szczyt albo pogrzebać całe studio.",
    cast: ["Michael De Santa", "Solomon Richards", "Miranda Cowan"],
    director: "Richards Majestic Studios",
    original: true,
    posterClass: "poster red",
  },
  {
    slug: "pacific-standard",
    title: "Pacific Standard",
    meta: "Thriller · 2026",
    year: "2026",
    maturity: "16+",
    runtime: "1h 54m",
    quality: "4K",
    match: "95%",
    genre: "Thriller",
    description:
      "Perfekcyjnie zaplanowany skok rozpada się w kilka minut, a grupa przestępców odkrywa, że ktoś sprzedał ich plan jeszcze zanim weszli do banku.",
    cast: ["D. Mercer", "L. Hayes", "M. Rowe"],
    director: "Jonas Ward",
    posterClass: "poster gold",
  },
  {
    slug: "the-last-take",
    title: "The Last Take",
    meta: "Drama · 2025",
    year: "2025",
    maturity: "16+",
    runtime: "2h 01m",
    quality: "4K",
    match: "92%",
    genre: "Drama",
    description:
      "Starzejący się reżyser dostaje jedną ostatnią szansę na film, który ma uratować jego nazwisko i rozpadające się studio.",
    cast: ["A. Sinclair", "J. Moore", "R. Klein"],
    director: "Elaine Mercer",
    posterClass: "poster blue",
  },
  {
    slug: "san-andreas",
    title: "San Andreas",
    meta: "Action · 2026",
    year: "2026",
    maturity: "16+",
    runtime: "2h 18m",
    quality: "4K HDR",
    match: "91%",
    genre: "Action",
    description:
      "Od Los Santos po Blaine County — jeden dzień, jedna ucieczka i cały stan na krawędzi chaosu.",
    cast: ["J. Kane", "N. Vega", "T. Rivers"],
    director: "Richards Majestic Action Unit",
    posterClass: "poster orange",
  },
  {
    slug: "after-hours",
    title: "After Hours",
    meta: "Mystery · 2025",
    year: "2025",
    maturity: "18+",
    runtime: "1h 48m",
    quality: "4K",
    match: "89%",
    genre: "Mystery",
    description:
      "Po zamknięciu klubów Los Santos zaczyna żyć drugim życiem. Reporter trafia na historię, której nikt nie chce zobaczyć rano.",
    cast: ["M. Cross", "V. Hale", "S. Novak"],
    director: "Iris Cole",
    posterClass: "poster purple",
  },
  {
    slug: "mirror-park",
    title: "Mirror Park",
    meta: "Comedy · 2026",
    year: "2026",
    maturity: "13+",
    runtime: "1h 37m",
    quality: "HD",
    match: "87%",
    genre: "Comedy",
    description:
      "Nowy lokator Mirror Park próbuje zacząć spokojne życie. Problem w tym, że jego sąsiedzi mają zupełnie inny plan.",
    cast: ["E. Price", "K. Mills", "B. Foster"],
    director: "Ronnie Blake",
    posterClass: "poster green",
  },
  {
    slug: "red-carpet",
    title: "Red Carpet",
    meta: "Original · Drama",
    year: "2026",
    maturity: "16+",
    runtime: "8 odcinków",
    quality: "4K",
    match: "97%",
    genre: "Drama",
    description:
      "Za każdą premierą stoi wojna o nazwiska, kontrakty i wpływy. Serial o ludziach, którzy sprzedają marzenia całemu Vinewood.",
    cast: ["C. Monroe", "E. Shaw", "D. Bennett"],
    director: "Majestic Television",
    original: true,
    posterClass: "poster crimson",
  },
  {
    slug: "southbound",
    title: "Southbound",
    meta: "Original · Crime",
    year: "2026",
    maturity: "18+",
    runtime: "10 odcinków",
    quality: "4K",
    match: "96%",
    genre: "Crime",
    description:
      "Młody kierowca zaczyna od drobnych zleceń na południu Los Santos. Każda kolejna trasa prowadzi go głębiej w cudzy biznes.",
    cast: ["R. Lewis", "T. Cole", "M. Diaz"],
    director: "Majestic Television",
    original: true,
    posterClass: "poster slate",
  },
  {
    slug: "studio-4",
    title: "Studio 4",
    meta: "Original · Documentary",
    year: "2026",
    maturity: "13+",
    runtime: "1h 42m",
    quality: "4K",
    match: "94%",
    genre: "Documentary",
    description:
      "Kamery po raz pierwszy zaglądają za kulisy największego planu Richards Majestic i pokazują, jak naprawdę powstaje kino w Vinewood.",
    cast: ["Richards Majestic Crew"],
    director: "Majestic Documentary Unit",
    original: true,
    posterClass: "poster amber",
  },
  {
    slug: "no-signal",
    title: "No Signal",
    meta: "Original · Thriller",
    year: "2026",
    maturity: "16+",
    runtime: "6 odcinków",
    quality: "4K",
    match: "93%",
    genre: "Thriller",
    description:
      "Miasto traci łączność na dziewięć minut. Dla większości to awaria. Dla jednej osoby — początek polowania.",
    cast: ["N. Hart", "J. Stone", "A. Kim"],
    director: "Majestic Television",
    original: true,
    posterClass: "poster navy",
  },
  {
    slug: "boulevard",
    title: "Boulevard",
    meta: "Original · Romance",
    year: "2026",
    maturity: "13+",
    runtime: "1h 51m",
    quality: "4K",
    match: "90%",
    genre: "Romance",
    description:
      "Dwie osoby z zupełnie różnych stron Vinewood spotykają się na jednym planie filmowym i szybko odkrywają, że kamera nie jest jedyną rzeczą, przed którą trudno coś ukryć.",
    cast: ["S. Lane", "A. Brooks"],
    director: "Laura Kent",
    original: true,
    posterClass: "poster wine",
  },
  {
    slug: "the-producer",
    title: "The Producer",
    meta: "Original · Drama",
    year: "2026",
    maturity: "16+",
    runtime: "2h 09m",
    quality: "4K",
    match: "92%",
    genre: "Drama",
    description:
      "Producent, który przez lata tworzył gwiazdy, nagle musi uratować własną karierę przed skandalem, którego nie da się wyciąć w montażu.",
    cast: ["V. Stone", "M. Laurent", "K. Young"],
    director: "Richards Majestic Studios",
    original: true,
    posterClass: "poster bronze",
  },
  {
    slug: "meltdown",
    title: "Meltdown",
    meta: "Classic · 2013",
    year: "2013",
    maturity: "18+",
    runtime: "1h 47m",
    quality: "HD",
    match: "88%",
    genre: "Drama / Action",
    description:
      "Kultowy klasyk Richards Majestic. Film, który miał być kolejną produkcją studia, a stał się jednym z symboli Vinewood.",
    cast: ["Milton McIlroy", "Anton Beaudelaire"],
    director: "Solomon Richards",
    posterClass: "poster mono",
  },
  {
    slug: "deep-inside",
    title: "Deep Inside",
    meta: "Classic · 2013",
    year: "2013",
    maturity: "18+",
    runtime: "1h 39m",
    quality: "HD",
    match: "84%",
    genre: "Classic",
    description: "Archiwalna produkcja Vinewood z katalogu Richards Majestic.",
    cast: ["Richards Majestic Cast"],
    director: "Richards Majestic Studios",
    posterClass: "poster teal",
  },
  {
    slug: "capolavoro",
    title: "Capolavoro",
    meta: "Classic · 2012",
    year: "2012",
    maturity: "16+",
    runtime: "2h 03m",
    quality: "HD",
    match: "86%",
    genre: "Classic",
    description: "Jedna z najbardziej rozpoznawalnych starszych produkcji w katalogu Majestic+.",
    cast: ["Richards Majestic Cast"],
    director: "Richards Majestic Studios",
    posterClass: "poster ivory",
  },
  {
    slug: "the-simian",
    title: "The Simian",
    meta: "Classic · 2011",
    year: "2011",
    maturity: "13+",
    runtime: "1h 44m",
    quality: "HD",
    match: "82%",
    genre: "Classic",
    description: "Klasyka Vinewood dostępna w odrestaurowanej wersji na Majestic+.",
    cast: ["Richards Majestic Cast"],
    director: "Richards Majestic Studios",
    posterClass: "poster moss",
  },
  {
    slug: "an-american-divorce",
    title: "An American Divorce",
    meta: "Classic · 2010",
    year: "2010",
    maturity: "16+",
    runtime: "1h 55m",
    quality: "HD",
    match: "80%",
    genre: "Drama",
    description: "Dramat z archiwum Vinewood, dziś ponownie dostępny w katalogu Richards Majestic.",
    cast: ["Richards Majestic Cast"],
    director: "Richards Majestic Studios",
    posterClass: "poster dusk",
  },
  {
    slug: "water-torture-ix",
    title: "Water Torture IX",
    meta: "Classic · Horror",
    year: "2010",
    maturity: "18+",
    runtime: "1h 31m",
    quality: "HD",
    match: "79%",
    genre: "Horror",
    description: "Dziewiąta część niesławnej serii horrorów, która przez lata obrastała legendą w Vinewood.",
    cast: ["Richards Majestic Cast"],
    director: "Richards Majestic Studios",
    posterClass: "poster black",
  },
];

export const getTitle = (slug: string) => titles.find((item) => item.slug === slug);

export const rows = [
  {
    title: "Popularne teraz",
    slugs: [
      "vinewood-nights",
      "pacific-standard",
      "the-last-take",
      "san-andreas",
      "after-hours",
      "mirror-park",
    ],
  },
  {
    title: "Majestic+ Originals",
    slugs: ["red-carpet", "southbound", "studio-4", "no-signal", "boulevard", "the-producer"],
  },
  {
    title: "Klasyki Vinewood",
    slugs: ["meltdown", "deep-inside", "capolavoro", "the-simian", "an-american-divorce", "water-torture-ix"],
  },
];
